class Constants {
  double deviceHeight = 803.6363636363636;
  double deviceWidth = 392.72727272727275;
  String url = 'https://f248-34-143-168-214.ngrok-free.app',
      biggerUrl = 'https://fcd2-34-125-55-159.ngrok-free.app';
  List<String> stationList = [
    'CHHATRAPATI Shivaji Terminus',
    'Kalyan',
    'Panvel',
    'Nasik road',
    'Solapur',
    'Manmad',
    'Gulbarga',
    'Akola',
    'Jalgaon',
    'Miraj',
    'Sainagar sirdih',
    'Kolhapur',
    'Badnera',
    'Khandawa',
    'Kopargaon',
    'Daud',
    'Ahmad nagar',
    'Wardha',
    'Shegaon',
    'Amrawati',
    'BALHARSHAH',
    'Lonavala',
    'Chandrapur',
    'Latur',
    'Betul',
    'Burhanpur',
    'Kurduwadi',
    'Chalisgaon',
    'Malkapur',
    'Sewagram',
    'Bhiwandi Road',
    'wadi',
    'Dombivali',
    'Badalapur',
    'Ghatkopar',
    'Kurla',
    'Ambarnath',
    'Mankhurd',
    'Mulund',
    'Mumbra',
    'Belapur',
    'Titwala',
    'Bhandup',
    'Nerul',
    'Vashi',
    'Kharghar',
    'Govandi',
    'Ulhasnagar',
    'Vikhroli',
    'Kalwa',
    'Byculla',
    'Sion',
    'Aeroli',
    'Karjat',
    'Chembur',
    'Guru Teg bahadur nagar',
    'Ghansoli',
    'Mansoravar',
    'Sanpada',
    'Sealdah',
    'Kolkatta terminal',
    'Bhagalpur',
    'Asansol',
    'Barddhman',
    'Naihati',
    'Malda Town',
    'Jasidih',
    'Durgapur',
    'Jamalpur',
    'Rampurhat',
    'Bandel Jn.',
    'New Farakka',
    'Madhupur',
    'Bolpur',
    'Berhampur court',
    'Sultanganj',
    'Raniganj',
    'Andal',
    'Krishnanagar city',
    'Barackpur',
    'Srirampur',
    'Dum Dum Jn.',
    'Sodepur',
    'Baruipur jn.',
    'Srirampur',
    'Rishra',
    'Konnagar',
    'Barasat jn.',
    'Belghoria',
    'Subhasgram',
    'Shyamngar',
    'Bidhannagar',
    'Habra',
    'Madhyamgram',
    'Sheoraphuli',
    'Ranaghat jn.',
    'Khardah',
    'Chakdah',
    'Patna',
    'Muzzafarpur',
    'Mughalsarai',
    'Gaya',
    'Dhanbad',
    'Darbhanga',
    'Rajendra Nagar Terminal',
    'Patliputra',
    'Samastipur',
    'Saharsa',
    'Ara',
    'Buxar',
    'Danapur',
    'Barauni Jn.',
    'Hajipur',
    'Koderma',
    'Banmankhi',
    'Dehri On Sone',
    'Kiul',
    'Khagaria',
    'Raxaul',
    'Sasaram',
    'Bettiah',
    'Jainagar',
    'Parasnath',
    'Madhubani',
    'Daltengunj',
    'Bakhtiyarpur',
    'Anugrah Narayan Road',
    'Sugauli',
    'Narkatiaganj',
    'Begusarai',
    'Sakari Jn',
    'Patna Sahib',
    'Sitamadhi',
    'Jamui',
    'Mokama',
    'Jhanja',
    'Singrauli',
    'Bhabhua Road',
    'Garhwa Road',
    'Mansi Jn.',
    'Dildarnagar',
    'Bagha',
    'Naugachia',
    'Sonepur',
    'Barkakana',
    'Jahanabad',
    'Taregana',
    'Fatuha',
    'Bihta',
    'Barh',
    'Puri',
    'Brahmapur',
    'Cuttack',
    'Viizanagaram',
    'Sambalpur',
    'Khurda Road',
    'Srikakulam',
    'Bhadrak',
    'Palasa',
    'Rayagada',
    'Jajpur-Keonjhar road',
    'Duvvada',
    'Bolangir',
    'Titlagrah',
    'Balugaon',
    'Kesinga',
    'Delhi',
    'Jammu Tavi',
    'Varanasi',
    'Lucknow',
    'Ludhiana Jn',
    'Haridwar',
    'Ambala Cantt.',
    'Sonipat',
    'Bareilly',
    'Dehradun',
    'Shri Mata  Vaisno devi Katra',
    'Moradabad',
    'Haharanpur',
    'Faizabad',
    'Bathinda',
    'Pathankot Jn',
    'Meerut City',
    'Sultanpur',
    'Jalandhar City',
    'Shahjahanpur',
    'Kalka',
    'Pratapgrah',
    'Shahgunj',
    'Firozpur Cantt',
    'Jaunpur',
    'Akbarpur',
    'Raebareli',
    'Roorkee',
    'Rohtak',
    'raichu',
    'Muzaffar Nagar',
    'Phagwara Jn.',
    'Palwal',
    'Rampur',
    'Udhampur',
    'Bhadohi',
    'Raj Pura',
    'Janghai',
    'Paryag',
    'Pathan kot Jn',
    'Hapur',
    'Unnao',
    'Sirhind',
    'Kurukshetra',
    'Barabanki',
    'Jaunpur City',
    'Patiala',
    'Ballabhgrah',
    'Ayodhya',
    'Amethi',
    'Chandausi',
    'Najibabad',
    'Abhohar Jn',
    'Sahibabad',
    'Bahdurgrah',
    'Nangloi',
    'Narela',
    'Tughlakabad',
    'Modinagar',
    'Noli',
    'Ganaur',
    'Faridabad New Town',
    'Pataudi road',
    'Braut',
    'Amroha',
    'Palam',
    'Delhi sadar bazar',
    'Jhansi',
    'Mathura',
    'Agra Fort',
    'Aligarh',
    'Chheoki',
    'Mirzapur',
    'Etawah',
    'Tundala',
    'Banda',
    'Morena',
    'Lalitpur',
    'Chitrakut Dham',
    'Mahoba',
    'Fatehpur',
    'Raja ki Mandi',
    'Manikpur',
    'Orai',
    'Khajuraho',
    'Phaphund',
    'Datia',
    'Dholpur Jn.',
    'Dabra',
    'Dadri',
    'Khurja',
    'Gorakhpur Jn',
    'Lucknow Jn',
    'Chhapra Jn',
    'Siwan',
    'Gonda Jn',
    'Manduwadih',
    'Basti',
    'Azamgrah',
    'Ballia',
    'Mau Jn',
    'Deoria Sadar',
    'Kathgodam',
    'Khalilabad',
    'Farrukhabad',
    'Ghazipur City',
    'Rudrapur Ciry',
    'Betlthara Road',
    'Badshahnagar',
    'Kasganj Jn.',
    'Kannauj',
    'Varanasi',
    'Bhatni',
    'Lalkuan Jn.',
    'Haldwani',
    'Mankapur Jn.',
    'Kashipur',
    'Pilibhit Jn.',
    'Bareilly City',
    'Guwahati',
    'New Jalpaiguri',
    'Katihar',
    'Kamakhya',
    'Dimapur',
    'Kishanganj',
    'New Coochbehar',
    'New Tinsukia',
    'Dibrugarh Town',
    'New Bongaigaon',
    'Rangiya Jn.',
    'Mariyani Jn.',
    'New Alipurduar',
    'Barsoi Jn.',
    'Dibrugarh',
    'Silchar',
    'Jogbani',
    'Lumding',
    'Raiganj',
    'Barpeta Road',
    'Alipurduar Jn.',
    'Dhupguri',
    'Kokrajhar',
    'Siliguri Jn.',
    'Purnea',
    'Araria Court',
    'Bikaner',
    'Abu Road',
    'Rewari',
    'Alwar',
    'Falna',
    'Sri Ganga Nagar',
    'Hisar',
    'Jaisalmer',
    'Bhilwara',
    'Bandikui',
    'Suratgarh',
    'Nagaur',
    'Marwar Jn.',
    'Pali Marwar',
    'Barmer',
    'Bhagar Ki Kothi',
    'Lalgarh',
    'Hanumangarh Jn.',
    'Bhiwani',
    'Merta Road',
    'Dausa',
    'Kishangarh',
    'Phulera',
    'Durgapura',
    'Beawar',
    'Sirsa',
    'Chennai Central',
    'Chennai Egmore',
    'Tambram',
    'Coimbatore Jn.',
    'Tiruvananthapuram Central',
    'Madurai Jn.',
    'Kozhikkode',
    'Katpadi',
    'Thrisur',
    'Chengalpattu Jn.',
    'Arakkonam Jn.',
    'Tiruvallur',
    'Tiruchchirappalli Jn',
    'Tirunelveli Jn.',
    'Mangalore Central',
    'Erode Jn',
    'Salem Jn.',
    'Kannur',
    'Eraniel',
    'Tiruppur',
    'Aluva',
    'Palakkad jn',
    'Kollam Jn',
    'Kottayam',
    'Shoranur Jn',
    'Chengannur',
    'Nagercoil Jn.',
    'Kayankulam Jn',
    'Thalassery',
    'Thanjavur Jn',
    'Mangalore Jn',
    'Dindigul Jn',
    'Rameswaram',
    'Tutikorin',
    'Jolarpattai',
    'Tirur',
    'Villupuram Jn',
    'Kochuvalli',
    'Alppuzha',
    'Perambur',
    'Mambalam',
    'Guduvancheri',
    'Perungalathur',
    'Kanniyakumari',
    'Vadakara',
    'kasargod',
    'Tiruvalla',
    'kumbakonam',
    'Payyannur',
    'Kovilpatti',
    'Virudhunagar Jn',
    'Mayiladuthurai Jn',
    'Nagappattinam',
    'Kanhangad',
    'Karur Jn.',
    'Ramanathapuram',
    'Kuttipuram',
    'Mettupalaiyam',
    'Changanacheri',
    'Varkalashivagiri',
    'Tiruttani',
    'Singaperumalkoil',
    'Angamali for Kaladi',
    'Hyderabad',
    'Kacheguda',
    'Huzur Saheb Nanded',
    'Rajahmundry',
    'Aurangabad',
    'Renigunta',
    'Guntur',
    'Warangal',
    'Samalkot',
    'Kazipet Jn',
    'Ongole',
    'Khammam',
    'Guntakal',
    'Gudur',
    'Kakinada Tn.',
    'Raichur',
    'Parbhani',
    'Nagarsol',
    'Tenali',
    'Anatpur',
    'Nizamabad',
    'Yadgir',
    'Eluru',
    'Bhimavaram Tn.',
    'Cuddapah',
    'Lingampalli',
    'Kurnool Tn',
    'Anakapalli',
    'Jalna',
    'Tadepalligudem',
    'Chirala',
    'Tuni',
    'Manchiryal',
    'Bidar',
    'Adoni',
    'Kakinada Port (new)',
    'Ramagundam',
    'Dharmavaram',
    'Narasapur',
    'Bhadrachalam Rd.',
    'Mantralayam Rd.',
    'Gudivada',
    'Mahbubabad',
    'Begumpet',
    'Nandyal',
    'Tandur',
    'Chittoor',
    'Vikarabad',
    'Repalli',
    'Tatanagar',
    'Kharagpur',
    'Rourkela',
    'Hatia',
    'Shalimar',
    'Jharsuguda',
    'Bokaro Steel City',
    'Balasore',
    'Chakradharpur',
    'Purulia Jn.',
    'Digha',
    'Bankura Jn.',
    'Midnapur',
    'Adra',
    'Jhargram',
    'Raipur',
    'Bilaspur',
    'Durg',
    'Gondia',
    'Raigharh',
    'CPH',
    'Anuppur',
    'Rajnandgaon',
    'Shahdol',
    'Bhatapara',
    'Korba',
    'Bhilai Power House',
    'Ambikapur',
    'Itwari',
    'Dongargadh',
    'Mysore',
    'Hubli Junction',
    'Krishnarajapuram',
    'Vasco-da-gama',
    'Bellary Jn.',
    'Davangere',
    'Bangarapet',
    'Mandya',
    'Hospet Jn.',
    'Kengeri',
    'Bijapur',
    'Srisatyasaiprashanthinilayam',
    'Shimoga Tn.',
    'Gadag Jn.',
    'Arsikere',
    'Yelahanka',
    'Hosur',
    'Tumkur',
    'Malur',
    'Channapatna',
    'Ramanagaram',
    'Whitefield',
    'Nanjangud Tn',
    'Kuppam',
    'Vadodara Jn.',
    'Ujjain',
    'Navsari',
    'Rajkot',
    'Vapi',
    'Ratlam',
    'Jamnagar',
    'Bharuch Jn.',
    'Gandhidham',
    'Bhuj',
    'Anand',
    'Chittorgarh',
    'Ankleshwar',
    'Nadiad',
    'Bilimora',
    'Veraval',
    'Bhavnagar',
    'Dwarka',
    'Dahod',
    'Nagda',
    'Surendranagar',
    'Dewas',
    'Junagarh',
    'Wankaner',
    'Viramgam',
    'Samakhiali',
    'Nimach',
    'Kosamba',
    'Mahemadabad & Kheda Road',
    'Botad',
    'Miyagam Karjan Jn.',
    'Umbergaon',
    'Kim',
    'Virar',
    'Bhayandar',
    'Churchgate',
    'Vasai Road',
    'Nallasopara',
    'Malad',
    'Goregaon',
    'Vaitarana',
    'Kandivali',
    'Vile Parley',
    'Boisar',
    'Mira Road',
    'Santacruz',
    'Jogeshwari',
    'Palghar',
    'Dahisar',
    'Mahim',
    'Khar Road',
    'Grant Road',
    'Dahanu Raod',
    'Elphinstone Road',
    'Charni Road',
    'Jabalpur',
    'Satna',
    'Katni',
    'Rewa',
    'Sawaimadhopur',
    'Saugor',
    'Bina',
    'Bharatpur',
    'Maihar',
    'Damoh',
    'Guna',
    'Pipariya',
    'Gangapur City',
    'Vidisha',
    'Hoshangabad',
    'Narshinghpur',
    'Hindaun City',
    'Ganjbasoda',
    'Dakaniya Talav',
    'Pragati Maidan',
    'Daya Basti',
    'Kirti Nagar',
    'Naraina Vihar',
    'Delhi Inderpuri',
    'Brar Square',
    'Sardar Patel Marg',
    'Sarojini Nagar',
    'Lodhi Colony',
    'Sewa Nagar',
    'PALAVANTANGAL',
    'AVADI',
    'BAGNAN',
    'PANSKURA',
    'MECHEDA',
    'Velachery',
    'Perungudi',
    'Taramani',
    'Thiruvanmiyur',
    'Indira Nagar',
    'Kasturba Nagar',
    'Kotturpuram',
    'Greenways Road',
    'Mandaveli',
    'Thirumayilai',
    'Light House',
    'Thiruvallikeni',
    'Chepauk',
    'Chintadripet',
    'Chennai Park Town',
    'Guindy',
    'Saidapet',
    'Kodambakkam',
    'Nungambakkam',
    'Chetput',
    'Perambur Loco Works',
    'Perambur Carriage Works',
    'Vyasarpadi Jeeva',
    'Tondiarpet',
    'Korukkupet',
    'Chennai Park',
    'Chennai Fort',
    'Washermanpet',
    'Basin Bridge',
    'Royapuram',
    'Moore Market Complex',
    'Chennai Beach',
    'Santoshpur',
    'Tollyganj',
    'Baghajatin',
    'Brace Bridge',
    'Dum Dum Cant',
    'Ballygunge',
    'Dhakuria',
    'Eden Garden',
    'Belur',
    'Tikiapara',
    'Liluah',
    'Birati',
    'Majerhat',
    'Khidirpur',
    'Princep Ghat',
    'Agarpara',
    'Santragachi Junction',
    'Vidyavihar',
    'Tilak Nagar',
    'Sewri',
    'Sandhurst Road',
    'Reay Road',
    'Matunga Road',
    'Matunga',
    'Marine Lines',
    'Bombay Masjid',
    'Mahalaxmi',
    'Dockyard Road',
    'Currey Road',
    'Cotton Green',
    'Chunabhatti',
    'Chinchpokli',
    'CBD Belapur',
    'Viveka Vihar',
    'Tilak Bridge',
    'Subji Mandi',
    'Shivaji Bridge',
    'Okhla',
    'Mongolpuri',
    'Delhi Sadarjung',
    'Kishanganj',
    'Badli',
    'Gomati Nagar',
    'Rani',
    'MEERUT CANTT.',
    'Jorhat Town',
    'Jagadhri',
    'Gomoh Jn.',
    'Coochbehar',
    'Bongaigaon',
    'Bhandara Road',
    'Una',
    'Kottipali',
    'Anandpur Sahib',
    'Aonla',
    'Bahraich',
    'Balaghat',
    'Jagdalpur',
    'Pangaon',
    'Bijnor',
    'Bulandshahar',
    'Churu',
    'Nagda',
    'Dhule',
    'Fatehpur Sikri',
    'Kotdwara',
    'Hathras',
    'Jhunjhunu',
    'Kangra',
    'Sirathu',
    'Johna',
    'Lakhimpur',
    'Lalganj',
    'Maharjganj',
    'Joginder Nagar',
    'Mibrik Tirath',
    'Mohanlal Ganj',
    'Dimapur',
    'Nandurbar',
    'Narasaraopet',
    'Nawada',
    'Patan',
    'Porbandar',
    'Robertshabj',
    'Saharanpur',
    'Shimla',
    'Sikar',
    'Sitapur',
    'Tezpur',
    'Pawapuri',
    'Kanyakumar'
  ];
  List<String> TTSLocaleIDS = [
    'hr-HR',
    'ko-KR',
    'mr-IN',
    'ru-RU',
    'zh-TW',
    'hu-HU',
    'sw-KE',
    'th-TH',
    'ur-PK',
    'nb-NO',
    'da-DK',
    'tr-TR',
    'et-EE',
    'pt-PT',
    'vi-VN',
    'en-US',
    'sq-AL',
    'sv-SE',
    'ar',
    'su-ID',
    'bn-BD',
    'bs-BA',
    'gu-IN',
    'kn-IN',
    'el-GR',
    'hi-IN',
    'he-IL',
    'fi-FI',
    'bn-IN',
    'km-KH',
    'fr-FR',
    'uk-UA',
    'pa-IN',
    'en-AU',
    'nl-NL',
    'fr-CA',
    'lv-LV',
    'sr',
    'pt-BR',
    'de-DE',
    'ml-IN',
    'si-LK',
    'cs-CZ',
    'is-IS',
    'pl-PL',
    'ca-ES',
    'sk-SK',
    'it-IT',
    'fil-PH',
    'lt-LT',
    'ne-NP',
    'ms-MY',
    'en-NG',
    'nl-BE',
    'zh-CN',
    'es-ES',
    'ja-JP',
    'ta-IN',
    'bg-BG',
    'cy-GB',
    'yue-HK',
    'es-US',
    'en-IN',
    'jv-ID',
    'id-ID',
    'te-IN',
    'ro-RO',
    'en-GB'
  ];
  List<String> TTSDisplay = [
    'Croatian',
    'Korean',
    'Marathi',
    'Russian',
    'Chinese (Traditional, Taiwan)',
    'Hungarian',
    'Swahili',
    'Thai',
    'Urdu',
    'Norwegian Bokmål',
    'Danish',
    'Turkish',
    'Estonian',
    'Portuguese (Portugal)',
    'Vietnamese',
    'English (United States)',
    'Albanian',
    'Swedish',
    'Arabic',
    'Sundanese',
    'Bengali (Bangladesh)',
    'Bosnian',
    'Gujarati',
    'Kannada',
    'Greek',
    'Hindi',
    'Hebrew',
    'Finnish',
    'Bengali (India)',
    'Khmer',
    'French (France)',
    'Ukrainian',
    'Punjabi (India)',
    'English (Australia)',
    'Dutch',
    'French (Canada)',
    'Latvian',
    'Serbian',
    'Portuguese (Brazil)',
    'German',
    'Malayalam',
    'Sinhala',
    'Czech',
    'Icelandic',
    'Polish',
    'Catalan',
    'Slovak',
    'Italian',
    'Filipino (Philippines)',
    'Lithuanian',
    'Nepali',
    'Malay (Malaysia)',
    'English (Nigeria)',
    'Dutch (Belgium)',
    'Chinese (Simplified, China)',
    'Spanish (Spain)',
    'Japanese',
    'Tamil (India)',
    'Bulgarian',
    'Welsh',
    'Cantonese (Hong Kong)',
    'Spanish (United States)',
    'English (India)',
    'Javanese',
    'Indonesian',
    'Telugu (India)',
    'Romanian',
    'English (United Kingdom)'
  ];
  List<String> STTDisplay = [
    'Afrikaans (South Africa)',
    'Albanian',
    'Amharic',
    'Arabic (Algeria)',
    'Arabic (Bahrain)',
    'Arabic (Egypt)',
    'Arabic (Israel)',
    'Arabic (Jordan)',
    'Arabic (Kuwait)',
    'Arabic (Lebanon)',
    'Arabic (Morocco)',
    'Arabic (Oman)',
    'Arabic (Palestine)',
    'Arabic (Qatar)',
    'Arabic (Saudi Arabia)',
    'Arabic (Tunisia)',
    'Arabic (United Arab Emirates)',
    'Armenian',
    'Azerbaijani',
    'Basque',
    'Bengali (Bangladesh)',
    'Bengali (India)',
    'Bulgarian',
    'Burmese',
    'Cantonese (Hong Kong)',
    'Catalan',
    'Croatian',
    'Czech',
    'Danish',
    'Dutch (Netherlands)',
    'English (Australia)',
    'English (Canada)',
    'English (Ghana)',
    'English (India)',
    'English (Indonesia)',
    'English (Ireland)',
    'English (Kenya)',
    'English (New Zealand)',
    'English (Nigeria)',
    'English (Philippines)',
    'English (Singapore)',
    'English (South Africa)',
    'English (Tanzania)',
    'English (Thailand)',
    'English (United Kingdom)',
    'English (United States)',
    'English (International)',
    'Estonian',
    'Filipino',
    'Finnish',
    'French (Belgium)',
    'French (Canada)',
    'French (France)',
    'French (Switzerland)',
    'Galician',
    'Georgian',
    'German (Austria)',
    'German (Belgium)',
    'German (Germany)',
    'German (Switzerland)',
    'Greek',
    'Gujarati (India)',
    'Hebrew (Israel)',
    'Hindi (India)',
    'Hungarian',
    'Icelandic',
    'Indonesian',
    'Italian (Italy)',
    'Italian (Switzerland)',
    'Japanese',
    'Javanese',
    'Kannada (India)',
    'Kazakh',
    'Khmer',
    'Kinyarwanda',
    'Korean',
    'Lao',
    'Latvian',
    'Lithuanian',
    'Macedonian',
    'Malay (Malaysia)',
    'Malayalam (India)',
    'Marathi (India)',
    'Mongolian',
    'Nepali',
    'Northern Sotho (South Africa)',
    'Norwegian (Norway)',
    'Persian (Iran)',
    'Polish',
    'Portuguese (Brazil)',
    'Portuguese (Portugal)',
    'Punjabi (India)',
    'Romanian',
    'Russian',
    'Serbian',
    'Sinhala',
    'Slovak',
    'Slovenian',
    'Sotho (South Africa)',
    'Spanish (Argentina)',
    'Spanish (Bolivia)',
    'Spanish (Chile)',
    'Spanish (Colombia)',
    'Spanish (Costa Rica)',
    'Spanish (Dominican Republic)',
    'Spanish (Ecuador)',
    'Spanish (El Salvador)',
    'Spanish (Guatemala)',
    'Spanish (Honduras)',
    'Spanish (Mexico)',
    'Spanish (Nicaragua)',
    'Spanish (Panama)',
    'Spanish (Paraguay)',
    'Spanish (Peru)',
    'Spanish (Puerto Rico)',
    'Spanish (Spain)',
    'Spanish (United States)',
    'Spanish (Uruguay)',
    'Spanish (Venezuela)',
    'Sundanese',
    'Swahili',
    'Swahili (Tanzania)',
    'Swati (South Africa)',
    'Swedish',
    'Tamil (India)',
    'Tamil (Malaysia)',
    'Tamil (Singapore)',
    'Tamil (Sri Lanka)',
    'Telugu (India)',
    'Thai',
    'Tsonga (South Africa)',
    'Tswana (Botswana)',
    'Turkish',
    'Ukrainian',
    'Urdu (India)',
    'Urdu (Pakistan)',
    'Uzbek',
    'Venda (South Africa)',
    'Vietnamese',
    'Xhosa (South Africa)',
    'Zulu (South Africa)',
    'Mandarin Chinese (China)',
    'Unknown Language1',
    'Unknown Language2',
    'Unknown Language3',
    'Unknown Language4'
  ];
  List<String> STTLocaleIDs = [
    'af_ZA',
    'sq_AL',
    'am_ET',
    'ar_DZ',
    'ar_BH',
    'ar_EG',
    'ar_IL',
    'ar_JO',
    'ar_KW',
    'ar_LB',
    'ar_MA',
    'ar_OM',
    'ar_PS',
    'ar_QA',
    'ar_SA',
    'ar_TN',
    'ar_AE',
    'hy_AM',
    'az_AZ',
    'eu_ES',
    'bn_BD',
    'bn_IN',
    'bg_BG',
    'my_MM',
    'yue_HK',
    'ca_ES',
    'hr_HR',
    'cs_CZ',
    'da_DK',
    'nl_NL',
    'en_AU',
    'en_CA',
    'en_GH',
    'en_IN',
    'en_ID',
    'en_IE',
    'en_KE',
    'en_NZ',
    'en_NG',
    'en_PH',
    'en_SG',
    'en_ZA',
    'en_TZ',
    'en_TH',
    'en_GB',
    'en_US',
    'en_001',
    'et_EE',
    'fil_PH',
    'fi_FI',
    'fr_BE',
    'fr_CA',
    'fr_FR',
    'fr_CH',
    'gl_ES',
    'ka_GE',
    'de_AT',
    'de_BE',
    'de_DE',
    'de_CH',
    'el_GR',
    'gu_IN',
    'iw_IL',
    'hi_IN',
    'hu_HU',
    'is_IS',
    'in_ID',
    'it_IT',
    'it_CH',
    'ja_JP',
    'jv_ID',
    'kn_IN',
    'kk_KZ',
    'km_KH',
    'rw_RW',
    'ko_KR',
    'lo_LA',
    'lv_LV',
    'lt_LT',
    'mk_MK',
    'ms_MY',
    'ml_IN',
    'mr_IN',
    'mn_MN',
    'ne_NP',
    'nso_ZA',
    'nb_NO',
    'fa_IR',
    'pl_PL',
    'pt_BR',
    'pt_PT',
    'pa_IN',
    'ro_RO',
    'ru_RU',
    'sr_RS',
    'si_LK',
    'sk_SK',
    'sl_SI',
    'nr_ZA',
    'st_LS',
    'st_ZA',
    'es_AR',
    'es_BO',
    'es_CL',
    'es_CO',
    'es_CR',
    'es_DO',
    'es_EC',
    'es_SV',
    'es_GT',
    'es_HN',
    'es_MX',
    'es_NI',
    'es_PA',
    'es_PY',
    'es_PE',
    'es_PR',
    'es_ES',
    'es_US',
    'es_UY',
    'es_VE',
    'su_ID',
    'sw_',
    'sw_TZ',
    'ss_ZA',
    'ss_SZ',
    'sv_SE',
    'ta_IN',
    'ta_MY',
    'ta_SG',
    'ta_LK',
    'te_IN',
    'th_TH',
    'ts_ZA',
    'tn_BW',
    'tn_ZA',
    'tr_TR',
    'uk_UA',
    'ur_IN',
    'ur_PK',
    'uz_UZ',
    've_ZA',
    'vi_VN',
    'xh_ZA',
    'zu_ZA',
    'cmn_C'
  ];
}
